layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: "slick752"
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: "sildvauresberg"
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
- name: Java
  web_url: https://www.oracle.com/technetwork/java/javase/downloads/index.html
  image_url: https://image.flaticon.com/icons/png/512/226/226777.png
- name: Spring
  web_url: https://spring.io
  image_url: https://github.com/spring-projects/spring-framework/blob/master/src/docs/asciidoc/images/spring-framework.png?raw=true
- name: Hazelcast
  web_url: https://hazelcast.com
  image_url: https://avatars3.githubusercontent.com/u/1453152?s=200&v=4
- name: Apache Kafka
  web_url: https://kafka.apache.org
  image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Apache_kafka.svg/1200px-Apache_kafka.svg.png
- name: Neo4j
  web_url: https://neo4j.com
  image_url: https://go.neo4j.com/rs/710-RRC-335/images/neo4j_logo_globe.png
- name: Apache Cassandra
  web_url: http://cassandra.apache.org
  image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Cassandra_logo.svg/1200px-Cassandra_logo.svg.png
  
